title = "Wes West"
baseURL = "https://loquacious-cocada-a527d9.netlify.app/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Seattle Area, WA"
email = "jmwest@gmail.com"
favicon = "/favicon.ico"
firstName = "Wes"
lastName = "West"
#phone = "1-555-555-1234"
profileImage = "img/Headshot.jpg"
showQr = false  # 20240511 When this is marked as true there's an error
showContact = true
#sections = ["skills","publications","creations","contributions","experience","education","blog"]
sections = ["publications","creations","contributions","experience","education","blog"]


[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/wes-west/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/weswest/"
name = "GitHub"

#[[params.handles]]
#link = "https://bitbucket.org/eddiewebb/"
#name = "Bitbucket"

#[[params.handles]]
#link = "https://stackoverflow.com/users/story/82880"
#name = "Stack Overflow"

#[[params.handles]]
#link = "https://keybase.io/edwardawebb"
#name = "Keybase"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"